In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:95% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<b><font color="red" size="5">ch.10 N차원 배열 다루기</font></b>
- N차원 배열: 하나 이상의 축(axis)을 가지는 동일한 자료형의 값들로 구성된 다차원 배열
- [numpy](https://numpy.org/doc/stable/)
- [numpy_API](https://numpy.org/doc/stable/reference/index.html)
- ↑ N차원 배열 객체 생성에 필요한 라이브러리
- 2차원 배열을 행렬개념
- numpy 패키지는 C언어로 구현되어 고성능 수치 계산 패키지
# 1절 넘파이 패키지

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [3]:
# np.arange(from, stop, step) : from 부터 stop앞까지 step씩 증감한 정수값을 배열로 생성
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 1.1 배열 속성

In [4]:
#arange(15): 0~14의 연속 정수 배열 (1차원)
#reshape(3, 5): 3행 5열로 재구성 → 2차원 배열
/ 
from numpy import arange #1차원 함수를 2차원 함수로 변경
a = arange(15).reshape(3,5)  #3행 5열짜리 2차원 배열로 변환 reshpae(행,열) 함수사용
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
type(a) #a변수의 타입

numpy.ndarray

In [6]:
a.dtype #a배열 요소의 type

dtype('int32')

In [7]:
a.dtype.name #자료형 이름을 문자열로 반환

'int32'

In [8]:
a.itemsize #한 요소의 bytesize

4

In [9]:
a.ndim #차원수(축수)

2

In [10]:
a.size #배열요소의 갯수

15

In [11]:
a.shape #배열의 구조(반드시 튜플로 들어가야함.)

(3, 5)

## 1.2 배열 변경(구조, 타입)

In [12]:
print('구조변경 전', a, sep='\n')
a.shape = (5, 3)
print('구조변경 후', a, sep='\n')

구조변경 전
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
구조변경 후
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [13]:
# 타입변경(이런식으로 데이터를 변경하면 안된다. 다른 함수를 써서 데이터를 변경해야 한다.)
a=arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a.dtype

dtype('int32')

In [15]:
a.itemsize

4

In [16]:
a.size, a.shape #12개 요소가 3행 4열짜리로 되어있음.

(12, (3, 4))

In [17]:
a.dtype = np.int64 # a배열을 읽을 때 64bit씩 읽는다.
a.dtype

dtype('int64')

In [18]:
a.itemsize

8

In [19]:
a.size, a.shape #a사이즈가 바뀌어있다.

(6, (3, 2))

In [20]:
a #데이터가 변조되었다.

array([[ 4294967296, 12884901890],
       [21474836484, 30064771078],
       [38654705672, 47244640266]], dtype=int64)

In [21]:
# 타입변경(이런식으로 바꾸어야 한다.)
a=arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a = a.astype(np.int64) #= a.astype('int64')
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [23]:
a.dtype

dtype('int64')

In [24]:
a.itemsize

8

In [25]:
a.size, 

(12,)

In [26]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [27]:
#1차원으로 변경(플랫한다고 표현함)
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [28]:
# 배열.ravel() 배열을 1차원으로 펼쳐서 반환하는 함수(원본 배열을 수정하지 않고, 새로운 1차원 배열뷰를 반환)
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

## 1.3 배열저장

In [29]:
a #를 저장하고 싶다면

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [30]:
#피클파일 저장하는것처럼 하기(머신러닝이라 num파일 저장시)(모든 파이썬 객체 저장 가능	파이썬 외부에서 읽기 어려움)
import pickle #파이썬 내장 모듈인 피클을 불러옵니다.
with open('data/ch10_a.pkl', 'wb') as f: #파일을 안전하게 열고 자동으로 닫아주는 구문입니다.
    pickle.dump(a, f) #	변수 a의 내용을 파일에 저장합니다.

In [31]:
# 저장된 배열 불러오기 (역직렬화)
with open('data/ch10_a.pkl', 'rb') as f:
    load_a=pickle.load(f)

In [32]:
load_a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [33]:
np.all(a == load_a) #a넘파이배열과 load_a 넘파이 배열이 같은지

True

In [34]:
#NumPy 전용 방식 (.npy), 저장 (빠르고, 넘파이 최적화	넘파이 외 객체는 저장 불가)
np.save('data/ch10_a.npy', a)

In [35]:
#불러오기
load_a2 = np.load('data/ch10_a.npy')
#비교
np.all(load_a2==a)

True

# 2절. 넘파이 배열
- array()함수 : 다른 파이썬 데이터 구조를 배열로 변환
- arange(), ones(), zeros(), empty()
- 랜덤값을 갖는 함수들...
## 2.1 array()함수로 넘파이 배열 만들기
- array(리스트나 튜플, dtype=np.xxx, copy=T/F)

In [36]:
a= np.array([2., 4, 6], dtype=np.int8) # 정수의 기본 타입은 int 32 #리스트, 튜플 등을 넘파이 배열로 변환
                                    #요소들의 데이터 타입을 int8로 지정 (1바이트 정수)
#정수만 있을 경우 → int32 (기본값)
#실수가 하나라도 있다면 → float64로 전체 변환
#문자가 하나라도 있다면 → 전체가 str로 변환

a

array([2, 4, 6], dtype=int8)

In [37]:
#리스트처럼 순서대로 값 추출 가능
#인덱스는 0부터 시작
a[0], a[1], a[2]

(2, 4, 6)

In [38]:
a.dtype

dtype('int8')

In [39]:
b =np.array([[1.3,2.4], 
             [4,5]])
b

array([[1.3, 2.4],
       [4. , 5. ]])

In [40]:
b.dtype

dtype('float64')

In [41]:
#2차원으로 만들기
b = np.array([1.3,2.4],[4,5], dtpe=np.float32).reshape(1,4)
b

TypeError: array() got an unexpected keyword argument 'dtpe'

In [ ]:
b.itemsize

In [ ]:
b.astype(np.float64)

In [ ]:
l = [[1, 2], [3.4, 4.5]]  # 2차원 리스트 정의

for row in l:  # 각 행(row)을 반복
    for data in row:  # 행 내의 각 데이터를 반복
        print(data, end='\t')  # 데이터를 탭 간격으로 출력 (가로 정렬)
    print()  # 각 행 출력 후 줄바꿈


In [ ]:
c = np.array([[1, 2], [3.4, 4.5]], dtype=np.float16)  # float16 형식의 2차원 넘파이 배열 생성

for i, row in enumerate(c):  # 행의 인덱스(i)와 행 데이터(row)를 함께 반복
    for j, item in enumerate(row):  # 열의 인덱스(j)와 각 요소(item)를 함께 반복
        print("{}행{}열:{}".format(i, j, item), end='\t')  # 위치와 값을 출력 (탭 간격)
    print()  # 각 행 출력 후 줄바꿈

In [ ]:
#인덱싱 슬라이싱한거처럼 이것도 똑같은짓을 할수있다.
c

In [ ]:
c = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype=np.int16)
c

In [ ]:
c[0,3]

In [ ]:
c[:, 1:3] # 모든행, 1열부터 3열앞까지

In [ ]:
# 0행 2열~4열까지
c[0, 2:5]

In [ ]:
# 모든행의 맨 마지막 열만 추출
c[:, -1]

In [ ]:
# 모든행의 맨 마지막 열을 제외한 추출
c[:, :-1]

In [ ]:
c = np.array([[1,2], [3,4]])
d = np.array(c, copy=False) #d=c 얕은복사
print('c=', c, sep='\n')
print('d=', d, sep='\n')
d[1, 0] = 3333
print('c=', c, sep='\n')
print('d=', d, sep='\n')
print('c주소= {}, d주소:{}'.format(id(c), id(d)))
#c값이 변경되었음

In [ ]:
c = np.array([[1,2], [3,4]])
d = np.array(c, copy=True) #d=c.copy() 깊은복사
print('c=', c, sep='\n')
print('d=', d, sep='\n')
d[1, 0] = 3333
print('c=', c, sep='\n')
print('d=', d, sep='\n')
print('c주소= {}, d주소:{}'.format(id(c), id(d)))
#c값이 그대로임.

## 2.2 기본값이 있는 배열만들기
- np.zeros( (tup) ) : 요소들이 다 0으로 채워짐.
- np.ones( (tupe) ) : 요소들이 다 1로 채워짐. 기본값이 float타입이 됨.
- np.full( tup, 기본값) : 요소들이 다 기본값
- np.empty(tup) : 요소들이 임의의 값(메모리상태에 따라 달라짐)
※ 위의 함수를 이용해서 생성된 배열을 기본 dtype이 float64. dtype속성 따라 지정 가능

In [ ]:
np.zeros( (3, 5) )

In [ ]:
x = np.ones((3,5))
x.dtype, x

In [ ]:
np.full( (2, 5), -256)

In [ ]:
np.empty((2,5)) #뭐가 나올지 나도 모름.

## 2.3 랜덤값을 갖는 배열 만들기
- np.random.random(tup) : 0부터 1미만의 균등분포를 갖는 랜덤값
- np.random.uniform(low=0, high=1.0, size=tup) : low부터 high미만의 균등분포를 갖는 랜덤값
- np.random.normal(loc=0, scale=1.0, size=tup) : 평균loc과 표준편차scale을 갖는 정규분포 랜덤값
- np.random.rand(n) : 균등분포의 1차원 난수 배열 발생(난수 n개)
- np.random.randn(n) : 표준정규분포(평균0, 표준편차1인 정규분포)의 1차원 난수배열 발생(난수 n개)
cf. np.random.randint(n) : 0부터 n미만의 정수 난수 1개 발생

In [ ]:
import matplotlib.pyplot as plt
x = np.random.rand(10000)
plt.figure(figsize=(15, 2)) # 그래프 크기 figsize=(가로, 세로)
plt.hist(x, bins=50)
plt.show()

In [ ]:
x = np.random.randn(10000)
plt.figure(figsize=(15, 2)) # 그래프 크기 figsize=(가로, 세로)
plt.hist(x, bins=50)
plt.show()

In [ ]:
#2차원 난수 배열
np.random.seed(7) # seed값을 맞추면 발생되는 난수 순서가 동일해짐
np.random.random( (2, 5) ) #0부터 1미만 균등분포 난수 배열

In [ ]:
np.random.uniform(-1, 10, (2,5)) #-1~10미만의 균등분포 난수 배열

In [ ]:
np.random.normal(10, 2, (2, 5)) #평균 10, 표준편차 2인 정규분포 난수 배열

## 2.4 연속된 값을 갖는 배열 만들기
- np.arange(from, stop, by, dtype) : from부터 stop앞까지 by씩 증감하는 정수배열
- np.linspace(from, to, count) : from부터 to까지(to포함) count개 숫자를 1차원 배열로 생성

In [ ]:
np.linspace(0, 2, 20)

In [ ]:
# linspace : 많은 수의 점들을 생성
x = np.linspace(0, 2*np.pi, 1000)
y = np.sin(x)

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(5, 2))
plt.plot(x, y)
plt.show

In [ ]:
np.linspace(0,2, 20).reshape(2, 10)

In [ ]:
np.arange(10, 30, 3, dtype=np.int8)

## 2.5 배열의 차원 변경하기
- 배열.reshape([면수,] 행수, 열수) : 배열의 형태(차원)를 바꿔서 새로운 배열을 만듬. (-1 사용 가능, 사용시 자동계산 가능)
- 배열.resize([면수,] 행수, 열수) : 배열의 크기와 형태를 직접 수정 (-1 불가), 원본이 수정됨.
- 배열.T : 배열을 전치(Transpose) 시킵니다. 즉, 행과 열을 뒤바꾼 배열을 만들어줍니다. T는 속성이라 함수처럼 ()를 붙이지 않습니다.
- 배열. transpose() : 배열을 전치(Transpose) 시켜주는 함수(전치행렬로 변환)
※ 실행결과가 출력되면 배열이 수정되지 않고, 실행결과가 없으면 배열 수정됨.

In [42]:
a = np.random.random( (2,3) )
a

array([[0.31735396, 0.14863928, 0.99812281],
       [0.87905091, 0.8840262 , 0.85004207]])

In [43]:
a = np.round(a * 10) #round : 반올림 / floor : 내림 / ceil : 올림
a

array([[ 3.,  1., 10.],
       [ 9.,  9.,  9.]])

In [44]:
a=a.reshape(3,2)
a

array([[ 3.,  1.],
       [10.,  9.],
       [ 9.,  9.]])

In [45]:
a.reshape(2, -1) # -1이 주어지면 해당 차원의 크기가 자동 계산

array([[ 3.,  1., 10.],
       [ 9.,  9.,  9.]])

In [46]:
a = a.reshape(-1, 1)
a

array([[ 3.],
       [ 1.],
       [10.],
       [ 9.],
       [ 9.],
       [ 9.]])

In [47]:
a.resize( (2,3) ) # 결과를 출력하지 않는 함수는 배열을 바꿈 -1불가

In [48]:
a

array([[ 3.,  1., 10.],
       [ 9.,  9.,  9.]])

In [49]:
a.ravel(), a.flatten()

(array([ 3.,  1., 10.,  9.,  9.,  9.]), array([ 3.,  1., 10.,  9.,  9.,  9.]))

In [50]:
a

array([[ 3.,  1., 10.],
       [ 9.,  9.,  9.]])

In [51]:
a.T #전치행렬(행과 열을 뒤바뀐 행렬)

array([[ 3.,  9.],
       [ 1.,  9.],
       [10.,  9.]])

In [52]:
a.transpose() #전치행렬(transpose() = T와 동일한 역할을 수행함.)

array([[ 3.,  9.],
       [ 1.,  9.],
       [10.,  9.]])

## 2.6 배열인쇄
- 배열 인쇄는 넘파이 배열 객체(ndarray)를 출력할 때, 보기 좋게 형식화해서 화면에 출력하는 기능을 말합니다.
- 넘파이는 배열을 차원에 따라 가로/세로로 정렬해서 출력합니다.
- 1차원: 한 줄에 출력
- 2차원: 행렬 형태로 행/열 표시
- 3차원 이상: 슬라이스 단위로 나눠 출력

In [56]:
# 배열이 너무 클 때 어떻게 돼?
# 예시 1 — 길이가 1001개인 1차원 배열
# 배열이 커서 출력이 안 될 경우
print(np.arange(1001))
# ... 으로 생략되어 출력됨

# 너무 긴 배열은 전부 출력하지 않음 (자동 요약)

[   0    1    2 ...  998  999 1000]


In [57]:
np.arange(10000).reshape(100, 100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [65]:
# 배열 출력 옵션 변경(인쇄할 사이즈를 10000, 최대치, 무한대)
import sys # 최대치 : sys.maxsize
#np.set_printoptions(threshold=10000)
#np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(threshold=np.inf)
# 커널 재시작시 threshold 값 복귀

In [67]:
#np.arange(10000).reshape(100, 100)

## 2.7 기본연산동작
- 산술 연산자(+, -, , / 등) 또는 비교 연산자(==, >, < 등)를 리스트나 배열 같은 자료구조에 적용했을 때의 동작 방식을 말합니다.
### 1) 배열

In [71]:
a = np.array([10, 20, 30, 40], dtype=np.int8)
b = np.arange(4)
print(a, a.dtype)
print(b, b.dtype)

[10 20 30 40] int8
[0 1 2 3] int32


In [76]:
c = a + b
c, c.dtype

(array([10, 21, 32, 43]), dtype('int32'))

In [80]:
a += b # a = a+b
a

array([10, 24, 38, 52], dtype=int8)

In [81]:
a = a + b
a, a.dtype

(array([10, 25, 40, 55]), dtype('int32'))

In [83]:
 a ** b # ** 승연산 a의 b승

array([     1,     25,   1600, 166375])

In [84]:
a < 30

array([ True,  True, False, False])

In [85]:
print(a[ [True, True, False, False] ])
print(a[a<30])

[10 25]
[10 25]


In [87]:
print(a)
print(b)
a * b

[10 25 40 55]
[0 1 2 3]


array([  0,  25,  80, 165])

### 2) 행렬(2차원 배열)의 곱(@, dot함수) 
cf*(요소별 곱)

In [90]:
a = np.array([[1, 2],
             [0, 1]])
b = np.array([[2, 0],
             [3, 4]])
a, b

(array([[1, 2],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [89]:
a * b

array([[2, 0],
       [0, 4]])

In [91]:
a @ b

array([[8, 8],
       [3, 4]])

In [92]:
# 행렬 : 자를 직사각형 모양으로 배열한 것입니다. 즉, 2차원 배열 그 자체
# 예시: 2행 3열짜리 행렬
A = np.array([[1, 2, 3],
              [4, 5, 6]])
# 행(row): 가로 방향 (예: 위에서 [1, 2, 3])
# 열(column): 세로 방향

In [94]:
# 행렬 곱
import numpy as np # 넘파이 모듈을 np라는 이름으로 불러오기

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.dot(A, B)  # 또는 A @ B *Python 3.5 이상에서는 @ 연산자도 사용 가능
#np.dot 두 배열(벡터 또는 행렬)**의 내적(dot product) 또는 **행렬 곱(matrix multiplication)**을 계산하는 함수
#**A 행렬의 행(row)**과 **B 행렬의 열(column)**을 서로 짝지어서 곱한 뒤 모두 더한 값이 결과 행렬의 원소가 됩니다.
print(C)

[[19 22]
 [43 50]]


In [95]:
#np.dot함수 사용 예시 추가
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))  # 출력: 1×4 + 2×5 + 3×6 = 32

32


In [96]:
#np.dot함수의 작동방식 설명
A = np.array([[1, 2],     # A: 2행 2열
              [3, 4]])

B = np.array([[5, 6],     # B: 2행 2열
              [7, 8]])

C = np.dot(A, B)
#C[0, 0] 계산 방법
# A의 0행: [1, 2]
# B의 0열: [5, 7]
#1×5 + 2×7 = 5 + 14 = 19
#C[0, 0] = 19

#C[0, 1] 계산 방법
#A의 0행: [1, 2]
#B의 1열: [6, 8]
#1×6 + 2×8 = 6 + 16 = 22
#C[0, 1] = 22

#이런식으로 연산하여 곱셈을 통해 생성된 숫자들을 더함.
#     B
#     ↓
#     5  6
#A →  7  8

#A[0,:] × B[:,0] → C[0,0]
#A[0,:] × B[:,1] → C[0,1]
#A[1,:] × B[:,0] → C[1,0]
#A[1,:] × B[:,1] → C[1,1]

### 3) 복합 대입연산자 사용
- 배열에서는 a=a+b와 a+=b 다소 다르게 작동

In [97]:
a=np.ones( (2,3), dtype=int ) # 2행 3열 int32배열
a

array([[1, 1, 1],
       [1, 1, 1]])

In [98]:
b = np.random.random( (2,3) ) # 2행 3열 float62 배열
b

array([[0.09781219, 0.14779588, 0.24485052],
       [0.27543825, 0.87526125, 0.1362464 ]])

In [100]:
a += b # a=b를 b에 넣는다.

In [99]:
a = a+b #a+b를 새로운 변수 a에 할당
a

array([[1.09781219, 1.14779588, 1.24485052],
       [1.27543825, 1.87526125, 1.1362464 ]])

### 4) 배열요소별 집계
- sum, min, max, mean, var(분산), std(표준편차)

In [101]:
a = np.array([[2, 2, 2, 3],
             [4, 3, 2, 1]])
a

array([[2, 2, 2, 3],
       [4, 3, 2, 1]])

In [102]:
# 배열요소 a를 전체 더함
print('전체합 :', np.sum(a), a.sum())

전체합 : 19 19


In [103]:
print('전체합 :', np.sum(a), a.sum())
print('전체최소 :', np.min(a), a.min())
print('전체최대 :', np.max(a), a.max())
print('전체평균 :', np.mean(a), a.mean())
print('전체분산 :', np.var(a), a.var())
print('전체표준편차 :', np.std(a), a.std())

전체합 : 19 19
전체최소 : 1 1
전체최대 : 4 4
전체평균 : 2.375 2.375
전체분산 : 0.734375 0.734375
전체표준편차 : 0.8569568250501305 0.8569568250501305


### 5) 배열 축별 집계
- sum, min, max, mean, var(분산), std(표준편차), argmax(최대값의 인덱스/제일 많이 사용됨.)

In [104]:
a

array([[2, 2, 2, 3],
       [4, 3, 2, 1]])

In [107]:
#axis : 넘파이 배열의 연산방향을 지정하는 값 axis=0은 열별 합을 구하는 함수, 1은 행별 합을 구하는 함수
#axis=0 (세로 ↓) : 1축을 고정으로 0축(행)들의 합
#[[2, 2, 2, 3],      → 열 방향으로 계산
# [4, 3, 2, 1]]
print('a의 열별 합 :', a.sum(axis=0), np.sum(a, axis=0))

#axis=1 (가로 →)
#[[2, 2, 2, 3],      → 행 방향으로 계산
# [4, 3, 2, 1]]

print('a의 행별 합 :', a.sum(axis=1), np.sum(a, axis=1))

a의 열별 합 : [6 5 4 4] [6 5 4 4]
a의 행별 합 : [ 9 10] [ 9 10]


In [111]:
# argmax : 지정한 축(axis)을 따라 배열에서 **최댓값의 "인덱스(위치)"**를 반환합니다.
#값 자체가 아니라 위치(index)를 반환
#a.argmax(axis=1)	각 행에서 최댓값의 열 인덱스
#a.argmax(axis=0)	각 열에서 최댓값의 행 인덱스
#axis로 **"어느 방향으로 비교할지"**를 정합니다.
print('a의 행별 최대값 위치:', a.argmax(axis=1), np.argmax(a, axis=1))

a의 행별 최대값 위치: [3 0] [3 0]


In [116]:
#3차원 배열의 축별 집계
b = np.arange(24).reshape(2,3,4) #2면 3행 4열
b, b.ndim

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 3)

In [117]:
# axis=0 : 1축과 2축을 고정하고 0축(0면, 1면)들의 합
b.sum(axis=0), np.sum(b, axis=0)

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]))

In [118]:
#axis=1 : 0축,2축 고정하고 1축(0행, 1행, 2행)들의 합
b.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [119]:
b.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

## 그외 요소별 계산하는 범용함수들
- 메모리나 시간을 효율적으로 사용할 수 있음.
- np.add(A, B, C) : C=np.add(A,B); C=A+B
- np.subtract(A, B, C) : C=np.subtract(A,B); C=A+B
- np.multiply(A, B, C) : C=np.multiply(A,B); C=A+B
- np.sqrt(배열) ; 요소별 제곱근 cf.math.sqrt(스칼라값)

In [122]:
a = np.array([1, 2])
b = np.array([3, 4])
c = a + b
c

array([4, 6])

In [123]:
np.add(a, b, c)
c

array([4, 6])

In [124]:
c = np.add(a, b)
c

array([4, 6])

In [126]:
#np.sqrt(배열 또는 스칼라값) math.sqrt(스칼라)
a, np.sqrt(a), np.sqrt(4)

(array([1, 2]), array([1.        , 1.41421356]), 2.0)

In [127]:
import math
math.sqrt(4)
math.sqrt(a)

TypeError: only size-1 arrays can be converted to Python scalars

## 2.9 브로드 케이스팅
- 서로 다른 크기의 배열 간 연산을 수행할 수 있도록 해주는 강력한 기능
- shape(모양)이 다른 두 배열 간 연산에서, 넘파이가 자동으로 작은 배열을 큰 배열에 맞춰서 복제(확장)하여 연산을 가능하게 하는 기능

In [130]:
# 1차원 배열
a = np.array([1,2,3])
b = 10
print(a + b)
print(np.add(a,b))

[11 12 13]
[11 12 13]


In [132]:
# 1차원 배열의 브로드케스팅
a = np.array([1,2,3])
b = np.array([10])
print(a + b)
print(np.add(a,b))

[11 12 13]
[11 12 13]


In [137]:
# 2차원 배열의 브로드케스팅
a = np.array([[0,0,0],
              [10,10,10],
              [20,20,20],
              [30,30,30]]) # 4행 3열
#b = np.array([1],
#             [2],
#             [3],
#             [4]) #4행 1열, 다만 이렇게 쓰면 거추장 스럽다.
b = np.array([1, 2, 3,4]) #4열에서 축증가를 통해 4행 1열로 바꾸려고 한다.

a + b

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [147]:
b = np.array([1, 2, 3,4]) #4열에서 축증가를 통해 4행 1열로 바꾸려고 한다.
# 방법 1 : b_1 = b.reshape(4,1)
# 방법 2(많이쓰임) : 
b_1 = b[:, np.newaxis]
# 방법 3 : b_1 = np.expand_dims(b, axis=1)
b_1

array([[1],
       [2],
       [3],
       [4]])

In [148]:
a + b[:, np.newaxis]

array([[ 1,  1,  1],
       [12, 12, 12],
       [23, 23, 23],
       [34, 34, 34]])

In [151]:
# a와 b의 모든 쌍의 조합에 대해 계산하고 싶을 때
a = np.array([2, 3, 4, 5])

b = np.array([10,20,30,40])
a+b[:, np.newaxis]
# np.newaxis는 배열의 차원을 1개 늘리는 문법
#b[:, np.newaxis]	b를 2차원 (세로방향)으로 변형
#a + b[:, np.newaxis]	b의 각 값에 a 전체를 더함
#결과	4×4 형태의 모든 조합 합

#   | +2 | +3 | +4 | +5
#10 | 12 | 13 | 14 | 15
#20 | 22 | 23 | 24 | 25
#30 | 32 | 33 | 34 | 35
#40 | 42 | 43 | 44 | 45

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

In [152]:
ax, bx = np.ix_(a,b)
ax+bx

array([[12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44],
       [15, 25, 35, 45]])

# 3절. 배열 합치기/분리하기
- 슬라이싱
- 두배열을 합치는 함수
- r_, c_
- 두 배열을 분리하는 함수
## 3.1 인덱싱과 슬라이싱
- 인덱싱에는 없는 인덱스 사용시 에러발생
- 슬라이싱에는 없는 인덱스 사용시 끝까지
- 음수 인덱스는 끝에서부터

In [153]:
a = np.arange(10)*3
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [154]:
a[20]

IndexError: index 20 is out of bounds for axis 0 with size 10

In [155]:
a = np.arange(20).reshape(5, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [156]:
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [159]:
# 모든 행의 마지막 열 앞까지 (모든 행=모든 0축의 경우 : 나...을 반드시 명시)
a[:, 0:-1] , a[..., :-1]

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18]]),
 array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18]]))

In [162]:
# 0~1행까지 모든열 추출(모든 열(1축)의 경우 생략 가능 :,... 사용 가능)
a[0:2, :], a[:2,...], a[:2]

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

In [163]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [167]:
# 마지막행의 데이터를 2차원으로 변경 -> 4행 1열
# 자주사용하므로 잘 기억할것!
# [16,17,18,19] 같은 1차원 배열을 (4, 1) 형태로 바꾸는 방법은
# [:, np.newaxis], .reshape(4, -1), np.expand_dims(..., axis=1) 이 있다.

a[-1][:, np.newaxis], a[-1].reshape(4, -1), np.expand_dims(a[-1], axis=1)

(array([[16],
        [17],
        [18],
        [19]]),
 array([[16],
        [17],
        [18],
        [19]]),
 array([[16],
        [17],
        [18],
        [19]]))

## 3.2 두 배열을 합치는 함수
- **vstack(tup) : 아래로 추가하는 방식으로 수직으로(행으로)쌓는것. 반드시 내부에는 튜플이 들어가야함.**
- **hstack(tup) : 옆으로 추가하는 방식으로 수평으로(열로) 쌓는것.  반드시 내부에는 튜플이 들어가야함.**
- **dstack(tup) : 마지막 출(열)을 쌓아 함침(차원증가)(depth stack)**

In [170]:
# vstack 예시
a = np.array([1,2,3])
b = np.array([4,5,6])
v = np.vstack( (a,b) )
print('vstack 아래로 합치기', v, v.shape, sep='\n')

vstack 아래로 합치기
[[1 2 3]
 [4 5 6]]
(2, 3)


In [171]:
# hstack 예시
h = np.hstack( (a,b) )
print('hstack 옆으로 합치기', h, h.shape, sep='\n')

hstack 옆으로 합치기
[1 2 3 4 5 6]
(6,)


In [172]:
#dstack예시
d=np.dstack( (a,b) )
print('dstack 축을 depth로 합치기', d, d.shape, sep='\n')

dstack 축을 depth로 합치기
[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [176]:
c = np.arange(24).reshape(2, 3, 4)
a, b = c[0], c[1]
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [177]:
v = np.vstack( (a,b) )
print('vstack 아래로 합치기', v, v.shape, sep='\n')
h = np.hstack( (a,b) )
print('hstack 옆으로 합치기', h, h.shape, sep='\n')
d=np.dstack( (a,b) )
print('dstack 축을 depth로 합치기', d, d.shape, sep='\n')

vstack 아래로 합치기
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4)
hstack 옆으로 합치기
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
(3, 8)
dstack 축을 depth로 합치기
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
(3, 4, 2)


In [179]:
np.concatenate( (a,b) , axis=0) #vstack( (a,b) )

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [180]:
np.concatenate( (a,b), axis=1 ) #hstack( (a,b) )

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

- **column_stack(tup) : 열단위로 합침 == hstack(tup)**
- **row_stack(tup) : 행단위로 합침 == vstack(tup)**
- **stack(tup, axis=0): axis=값에 따라 배열합침 axis값은 음수차원 가능**

In [181]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
np.column_stack( (a,b,c) )

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [182]:
np.row_stack( (a,b,c) )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
c = np.arange(24).reshape(2, 3, 4)
a, b = c[0], c[1]
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [184]:
np.stack( (a,b), axis=0) #0면 a, 1면 b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [186]:
np.stack( (a,b), axis=1 ) # 행(1축)끼리 합쳐서 면을 이룸

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [187]:
np.stack( (a,b), axis=-1 ) #a의 행과 b의 행을 열로 합쳐서 면을 이룸

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

## 3.3 r_, c_

In [189]:
a = np.array([1,2,3,4])
b = np.array([5,5,5,5])
c = np.array([6,6,6,6])
np.r_[a,b,c] # 행 합치기

array([1, 2, 3, 4, 5, 5, 5, 5, 6, 6, 6, 6])

In [190]:
np.r_[ [a], [b], [c] ]

array([[1, 2, 3, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [191]:
np.c_[a,b,c] #컬럼 쌓기

array([[1, 5, 6],
       [2, 5, 6],
       [3, 5, 6],
       [4, 5, 6]])

## 3.4 배열 분리하는 함수
- **vsplit(ary, 정수나 벡터) : stack의 반대라고 생각하면됨. 첫번째 축을 따라 분할**
- **hsplit(ary, 정수나 벡터) : 두번째 축을 따라 분할**
- **dsplit(ary, 정수나 벡터) : depth에 따라 나눔(3차원 이상에서만 동작)**
    - 정수 n : n개로 분리
    - [n] : n번째 인덱스를 기준으로
    - [m,n] : m번째, n번째 인덱스를 기점으로 분리

In [193]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [195]:
a_vsplit = np.vsplit(a, 3) #2개로 분리는 에러발생
a_vsplit

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [197]:
np.vsplit(a, [2]) #[2] : 2번 인덱스를 기점으로 분할

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [198]:
np.hsplit(a, 2) 

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [199]:
np.hsplit(a, 3) # a가 짝수열이므로 홀수열로 나누려고 하면 오류가 발생함. 정확히 딱 떨어지게 나눠야함.

ValueError: array split does not result in an equal division

In [201]:
np.hsplit(a, [2,3]) #[2,3]:분리될 기준 인덱스

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

- **split(ary, 갯수나 인덱스벡터, axis)**
    - axis=0 : vsplit() 동일
    - axis=1 : hsplit() 동일
    - axis=2 : 3차원 이상에서만 동작 dsplit() 동일
- **array_split(ary, 갯수나 인덱스벡터, axis)**
    - split과의 차이점은 나눠지지 않은 정수로도 사용 가능

In [203]:
a = np.arange(20).reshape(2, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [205]:
np.split(a, 2, axis=0) # 행분리

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [206]:
np.split(a, 2, axis=1) # 열분리

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [207]:
# np.split(a, 3, axis=1) # 열분리
np.array_split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [10, 11, 12, 13]]),
 array([[ 4,  5,  6],
        [14, 15, 16]]),
 array([[ 7,  8,  9],
        [17, 18, 19]])]